### ISSUE TITLE
Fedora 21

### ISSUE THREAD

**Issue by jgillich** [jgillich/brackets-rpm#18]
Due to a library update, the Fedora 21 package would need https://copr.fedoraproject.org/coprs/red/libgcrypt.so.11/ (take srpm and build it in the copr repo).

It should be depended on using a dist tag: https://fedoraproject.org/wiki/Packaging:DistTag

**Comment by yudrassil** [comment]
Same here,
for now i have found this solution to install brackets on my f21
http://abm.id.au/blog/2014/07/adobe-brackets-on-fedora/
i also needed this package:
https://copr.fedoraproject.org/coprs/red/libgcrypt.so.11/

To remove brackets just run
```
sudo rm -R ~/bin/brackets \
/opt/brackets \
/usr/bin/brackets \
/usr/share/doc/brackets \
/usr/share/icons/hicolor/scalable/apps/brackets.svg \
/usr/share/menu/brackets.menu
```

greets

**Comment by jgillich** [comment]
Its really not that complicated, just use the F20 package by setting:

    baseurl=https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-20-$basearch/

in the repo file. Anyway, the Linux support of Brackets is in a poor state, I might have some time to get the package working again soon but I can't make any promises. I found [Atom](https://atom.io/) to work a lot better on Linux, I would recommend everyone to take a look.

**Comment by Fnux** [comment]
I found another way, through fedy : 
https://satya164.github.io/fedy/

PS : I'm going to take a look for atom.

**Comment by kidwm** [comment]
@jgillich Will you update it to version 1.1 ?

**Comment by kxra** [comment]
there's also http://lighttable.com/

although personally i'd just like to see someone update the minimap plugin for gedit: 
https://github.com/jonocodes/GeditTextmap

**Comment by tori3852** [comment]
Hi @jgillich, what tools do you use to build source rpm? Could you also share exact command line?

**Comment by jgillich** [comment]
@tori3852 Just rpmbuild, see https://fedoraproject.org/wiki/How_to_create_an_RPM_package

**Comment by dacrhu** [comment]
Hi,

I was playing a lot and succeeded solve the problem.
Solution:
https://copr.fedoraproject.org/coprs/dacr/brackets/

compat-libudev0 - make a symlink
Brackets rpm did not make symlink further.
I put this dependece to spec of brackets (build and install).

(my English is bad, sry ;) )

**Comment by jgillich** [comment]
@dacrhu Can you post a diff of the spec file?

I just tried replacing LD_PRELOAD with LD_LIBRARY_PATH. Builds locally, fails on Copr. Lovely.

**Comment by jgillich** [comment]
Oh nevermind, I see now. Well, symlinking into `/usr/lib` is exactly what I want to avoid, the package is bad enough already.

**Comment by jgillich** [comment]
If anyone wants to help, please try to build on your machine and tell me how it went. Here is how:
```
sudo yum install @development-tools fedora-packager gtk2-devel npm nspr gyp desktop-file-utils
# on F21: also install compat-libgcrypt (provided by the brackets copr repo)
rpmdev-setuptree
curl -L https://github.com/jgillich/brackets-rpm/archive/master.tar.gz | tar -xvz -C ~/rpmbuild --strip-components=1
cd ~/rpmbuild/
bash fetch_source.sh 1.1 release-1.1 linux-1547
rpmbuild -ba ~/rpmbuild/SPECS/brackets.spec
```

**Comment by jgillich** [comment]
Seems like I've finally managed to make it work. Yay! :)
