### ISSUE TITLE
Application Window Not Minimizing Fedora 21

### ISSUE THREAD

**Issue by blastdan** [jgillich/brackets-rpm#21]
Hello,
I'm seeing strange behavior when I try and minimize brackets on Fedora 21

The shell windows will minimizing taking away the title bar, window resize options and the close button, however the Brackets application stays in an "Always on top" state, even staying above the lock screen animation. You can see the cursor blink, however you cannot interact with the application.

The application closes fine, maximizes fine, and seems to work fine besides this minimize issue.

Any idea what could be causing this?

Thanks.

**Comment by jgillich** [comment]
Sounds a lot like https://github.com/adobe/brackets/issues/10057. Closing because I don't think this is a packaging issue.
