### ISSUE TITLE
Is it neccessary to install nodejs package when using brackets?

### ISSUE THREAD

**Issue by hkskoglund** [jgillich/brackets-rpm#22]
Iam using iojs at the moment, and bracket package is dependent on nodejs package? Installing brackets will overwrite existing iojs binaries. It is really necessary to install the nodejs package if not building brackets? I found an internal Brackets-node process file in /usr/share/brackets. Starting brackets and 'pgrep -a Brackets-node' gives 12434 /usr/share/brackets/Brackets-node /usr/share/brackets/node-core.

**Comment by jgillich** [comment]
My initial plan was to use the system's node binary instead of the one that is pulled in during the build process, but I haven't done it yet, so the node dependency serves no purpose. Give me a sec, I'll just push an update that removes it.
