### ISSUE TITLE
Package for Fedora 22

### ISSUE THREAD

**Issue by satya164** [jgillich/brackets-rpm#23]
Fedora 22 is near release. Can you add Fedora 22 to the copr build?

**Comment by kmare** [comment]
well, F22 has been released, it would be really nice to be able to get brackets running again.

**Comment by jorg76440** [comment]
I just wanted to let you know that I had a Fedora 21 running under Virtualbox with Brackets installed via your repository and what a wonder : when I updated Fedora 21 to Fedora 22 with the official utility
, Brackets still works fine !

**Comment by Fnux** [comment]
Hi! I waiting for a brackets package for Fedora 22 ;) Is there any news about it ?

**Comment by emerham** [comment]
So I just built this repo on Fedora 22, made no changes to any script and it generated a f22 rpm file.  I don't know if there is anything that needs to be done other than updating the build servers to include a 22 release.

**Comment by JulienMcJay** [comment]
I've found out a solution how to fix this problem:

Replace the file /etc/yum.repos.d/_copr_jgillich-brackets.repo with this:

```
[jgillich-brackets]
name=Copr repo for brackets owned by jgillich
baseurl=https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-21-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/pubkey.gpg
enabled=1
```

**Comment by satya164** [comment]
@JulienMcJay It's just an workaround. Not a fix.

@emerham Care to collaborate on forking the project and making a new copr?

**Comment by JulienMcJay** [comment]
@satya164 Sorry. My English is not as good as it its. I'm from Germany, you know.

**Comment by satya164** [comment]
@JulienMcJay no issues :)

**Comment by emerham** [comment]
@satya164 I don't want to step on anyone's toes creating a new copr just for 22, but if the original maintainer has no objection I would be more than happy to create a new one.

**Comment by satya164** [comment]
@emerham I don't want it either, but it seems @jgillich made this copr for his personal use. So we need one for the community.

**Comment by jgillich** [comment]
Oh no need to fork, I just forgot to push a package for F22. Unfortunately I don't get email notifications for new issues.

**Comment by emerham** [comment]
@jgillich ok good, no need for me to redo all your work.

**Comment by satya164** [comment]
@jgillich Cool. Then. Thanks a lot :D

**Comment by emerham** [comment]
@jgillich I've got the src.rpm file for 22, if you want me to do a merge request

**Comment by jgillich** [comment]
@emerham Thanks but I'm already building, it will be up later today.

**Comment by phaux** [comment]
It still says that there's no repo for Fedora 22 when trying to `dnf install brackets`

**Comment by Fnux** [comment]
I just installed brackets on my f22. Through fedy (https://satya164.github.io/fedy/).
So it should be okay ?

**Comment by satya164** [comment]
@Fnux Currently Fedy installs Brackets from the F21 copr.

**Comment by Fnux** [comment]
It didn't work last week (Fedy said there was no package for f22). But it worked this morning ?

**Comment by satya164** [comment]
@Fnux I pushed an update to Fedy to use the F21 repo for brackets.
