### ISSUE TITLE
Please package Brackets 1.4

### ISSUE THREAD

**Issue by phayz** [jgillich/brackets-rpm#25]
Brackets 1.4 was literally *just* released and I've love to be able to use it. Please consider packaging Brackets 1.4.

**Comment by jgillich** [comment]
Done, thanks for the notice.

**Comment by phayz** [comment]
Thank you! Also... thanks to your repo I was able to easily and quickly package Brackets 1.4 on my Fedora 21 installation. I will continue to use your repo, of course.  :D
