### ISSUE TITLE
Package for Fedora 23

### ISSUE THREAD

**Issue by llaumgui** [jgillich/brackets-rpm#26]
Hi,

Fedora 23 is beta... Is it possible to package a version for F23 ?

Thx.

**Comment by jgillich** [comment]
Copr doesn't support F23 yet. Try installing the F22 package.

**Comment by llaumgui** [comment]
Strange, because some Copr proposes F23 (ie: https://copr.fedoraproject.org/coprs/heikoada/mailnag/).
Bracket is unstable since F23.

**Comment by jgillich** [comment]
Oh I'm sorry, they made some changes to the interface so I didn't look in the right place. I've initiated a F23 build.

Any details about the stability issue?

**Comment by jgillich** [comment]
Make sure you've installed compat-libgcrypt, I have to update the spec for F23.

**Comment by llaumgui** [comment]
Thx, work fine now on F23
