### ISSUE TITLE
Bracket 1.6

### ISSUE THREAD

**Issue by llaumgui** [jgillich/brackets-rpm#28]
Hi,

is it possible to build v1.6 ?

Thx.

**Comment by 1dot75cm** [comment]
https://copr.fedorainfracloud.org/coprs/mosquito/brackets/

**Comment by jgillich** [comment]
@1dot75cm Can I point people to your repo? I have very little interest in keeping this updated.

**Comment by 1dot75cm** [comment]
Okay thank you
