### ISSUE TITLE
Doesn't Open

### ISSUE THREAD

**Issue by alexmigf** [jgillich/brackets-rpm#29]
Don't know why but suddenly Brackets doesn't run.

`/usr/bin/brackets: error while loading shared libraries: libgcrypt.so.11: cannot open shared object file: No such file or directory`

I removed and installed again but didn't work.

**Comment by jgillich** [comment]
Make sure you have `compat-libgcrypt` (it should come with the package).

**Comment by alexmigf** [comment]
I have.

**Comment by alexmigf** [comment]
--best --allowerasing

Did the trick.
